name: NPM PackValid
description: A GitHub Actions workflow to check the existence of a plugin on npm.
author: NxtOpen
inputs:
  package-json-path:
    description: 'Path to the package.json file. Default is the root folder.'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Read package.json
      shell: bash
      id: read-package
      run: |
        if [ -z "${{ inputs.package-json-path }}" ]; then
          package_json_path="package.json"
        else
          package_json_path="${{ inputs.package-json-path }}"
        fi
        
        version=$(jq -r '.version' $package_json_path)
        echo "::set-output name=version::$version"
        echo "::set-output name=name::$(jq -r '.name' $package_json_path)"

    - name: Check Plugin Version
      shell: bash
      id: check-plugin
      run: |
        version=${{ steps.read-package.outputs.version }}
        npm view ${{ steps.read-package.outputs.name }}@$version version >/dev/null 2>&1
        if [ $? -eq 0 ]; then
          echo "Plugin exists with version $version"
          exit 1
        else
          echo "Plugin does not exist with version $version, proceeding..."
        fi

    - name: Plugin Exists
      shell: bash
      if: steps.check-plugin.outcome == 'failure'
      run: exit 1
